# -- GitHub Pages + MathJax config --
# Keep it minimal & compatible with github-pages build
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  parse_block_html: true
  hard_wrap: false
# If you already have other settings, merge these keys rather than replacing entirely.
